FROM node:24-slim

WORKDIR /main

RUN apt-get update -y && \
    apt-get install -y openssl ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copying root manifests
COPY package*.json ./
COPY .npmrc ./
COPY turbo.json ./
COPY apps/*/package.json ./apps/
COPY packages/*/package.json ./packages/

# Create workspace folders
RUN mkdir -p apps/server apps/web packages/db packages/eslint-config packages/lib packages/tailwind-config packages/types packages/typescript-config packages/ui

# Copy workspace manifests
COPY apps/server/package.json apps/server/
COPY apps/web/package.json apps/web/

COPY packages/db/package.json packages/db/
COPY packages/eslint-config/package.json packages/eslint-config/
COPY packages/lib/package.json packages/lib/
COPY packages/tailwind-config/package.json packages/tailwind-config/
COPY packages/types/package.json packages/types/
COPY packages/typescript-config/package.json packages/typescript-config/
COPY packages/ui/package.json packages/ui/


# install dependencies

RUN npm install 

# copy source code
COPY apps ./apps
COPY packages ./packages

