export const urlPath = {
  home: '/',
  signin: '/signin',
  dashboard: '/dashboard',
  contacts: '/contacts',
  chat: '/chat',
  addContact: 'add-contact',
  call: '/call',
};

export const WS_CONST = {
  AUTH_INIT: 'WS_AUTH_INIT',
  AUTH_SUCCESS: 'WS_AUTH_SUCCESS',
  AUTH_FAILED: 'WS_AUTH_FAILED',

  CONNECT: 'WS_CONNECT',
  DISCONNECT: 'WS_DISCONNECT',
  CLOSE: 'WS_CLOSE',
  ERROR: 'WS_ERROR',
};

export const CHAT_CONST = {
  CHAT: 'CHAT',
  USER_STATUS: 'USER_STATUS',
  TYPING: 'TYPING',
  NEW_CONVERSATION: 'NEW_CONVERSATION',
  UPDATE_CONVERSATION: 'UPDATE_CONVERSATION',

  CHAT_ERROR: 'CHAT_ERROR',
};

export const CALL_CONST = {
  CREATE_OFFER: 'CREATE_OFFER',
  CREATE_ANSWER: 'CREATE_ANSWER',
  ADD_ICE_CANDIDATE: 'ADD_ICE_CANDIDATE',

  INITIATE_CALL: 'INITIATE_CALL',
  INCOMING_CALL: 'INCOMING_CALL',
  USER_BUSY: 'USER_BUSY',
  USER_OFFLINE: 'USER_OFFLINE',

  CALL_ACCEPTED: 'CALL_ACCEPTED',
  CALL_REJECTED: 'CALL_REJECTED',
  CALL_TIMEOUT: 'CALL_TIMEOUT',
  CALL_ENDED: 'CALL_ENDED',

  CALL_ERROR: 'WS_ERROR',
};
